# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: todo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'todo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntodo.proto\"\x07\n\x05\x45mpty\"7\n\x11\x43reateTodoRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"Y\n\x11UpdateTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x14\n\x0cis_completed\x18\x04 \x01(\x08\"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"T\n\x0cTodoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x14\n\x0cis_completed\x18\x04 \x01(\x08\"0\n\x10TodoListResponse\x12\x1c\n\x05todos\x18\x01 \x03(\x0b\x32\r.TodoResponse2\xc0\x01\n\x0bTodoService\x12/\n\nCreateTodo\x12\x12.CreateTodoRequest\x1a\r.TodoResponse\x12%\n\x08GetTodos\x12\x06.Empty\x1a\x11.TodoListResponse\x12/\n\nUpdateTodo\x12\x12.UpdateTodoRequest\x1a\r.TodoResponse\x12(\n\nDeleteTodo\x12\x12.DeleteTodoRequest\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=14
  _globals['_EMPTY']._serialized_end=21
  _globals['_CREATETODOREQUEST']._serialized_start=23
  _globals['_CREATETODOREQUEST']._serialized_end=78
  _globals['_UPDATETODOREQUEST']._serialized_start=80
  _globals['_UPDATETODOREQUEST']._serialized_end=169
  _globals['_DELETETODOREQUEST']._serialized_start=171
  _globals['_DELETETODOREQUEST']._serialized_end=202
  _globals['_TODORESPONSE']._serialized_start=204
  _globals['_TODORESPONSE']._serialized_end=288
  _globals['_TODOLISTRESPONSE']._serialized_start=290
  _globals['_TODOLISTRESPONSE']._serialized_end=338
  _globals['_TODOSERVICE']._serialized_start=341
  _globals['_TODOSERVICE']._serialized_end=533
# @@protoc_insertion_point(module_scope)
